// Mocks generated by Mockito 5.4.6 from annotations
// in common_github_search/test/domain/use_cases/search_repositories_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:common_github_search/src/domain/entities/entities.dart' as _i2;
import 'package:common_github_search/src/domain/repositories/github_repository_interface.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchResult_0<T> extends _i1.SmartFake
    implements _i2.SearchResult<T> {
  _FakeSearchResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GitHubRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockGitHubRepositoryInterface extends _i1.Mock
    implements _i3.GitHubRepositoryInterface {
  MockGitHubRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SearchResult<_i2.GitHubRepository>> searchRepositories(
          _i2.SearchCriteria? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchRepositories,
          [criteria],
        ),
        returnValue: _i4.Future<_i2.SearchResult<_i2.GitHubRepository>>.value(
            _FakeSearchResult_0<_i2.GitHubRepository>(
          this,
          Invocation.method(
            #searchRepositories,
            [criteria],
          ),
        )),
      ) as _i4.Future<_i2.SearchResult<_i2.GitHubRepository>>);

  @override
  _i4.Future<_i2.GitHubRepository?> getRepositoryById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRepositoryById,
          [id],
        ),
        returnValue: _i4.Future<_i2.GitHubRepository?>.value(),
      ) as _i4.Future<_i2.GitHubRepository?>);

  @override
  _i4.Future<List<_i2.GitHubRepository>> getRepositoriesByUser(
          String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRepositoriesByUser,
          [username],
        ),
        returnValue: _i4.Future<List<_i2.GitHubRepository>>.value(
            <_i2.GitHubRepository>[]),
      ) as _i4.Future<List<_i2.GitHubRepository>>);
}
